// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gestion_etablissement.Data;

#nullable disable

namespace gestion_etablissement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251208015909_Etablissement")]
    partial class Etablissement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("gestion_etablissement.Model.Classe", b =>
                {
                    b.Property<int>("Id_classe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnneeScolaire")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Niveau")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id_classe");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("gestion_etablissement.Model.Cours", b =>
                {
                    b.Property<int>("Id_cours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date_Debut")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date_Fin")
                        .HasColumnType("TEXT");

                    b.Property<int>("Duree")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomMatiere")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Salle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id_cours");

                    b.ToTable("Cours");
                });

            modelBuilder.Entity("gestion_etablissement.Model.Directeur", b =>
                {
                    b.Property<int>("Id_directeur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id_utilisateur")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Poste")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id_directeur");

                    b.ToTable("Directeurs");
                });

            modelBuilder.Entity("gestion_etablissement.Model.Eleve", b =>
                {
                    b.Property<int>("Id_eleve")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date_naissance")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id_utilisateur")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("adresse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id_eleve");

                    b.ToTable("Eleves");
                });

            modelBuilder.Entity("gestion_etablissement.Model.EmploiDuTemps", b =>
                {
                    b.Property<int>("Id_emploiDuTemps")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id_emploiDuTemps");

                    b.ToTable("EmploiDuTemps");
                });

            modelBuilder.Entity("gestion_etablissement.Model.Professeur", b =>
                {
                    b.Property<int>("Id_professeur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id_utilisateur")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Specialite")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("grade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id_professeur");

                    b.ToTable("Professeurs");
                });

            modelBuilder.Entity("gestion_etablissement.Model.Utilisateur", b =>
                {
                    b.Property<int>("Id_utilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mot_de_passe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom_utilisateur")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TypeUtilisateur")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id_utilisateur");

                    b.ToTable("Utilisateurs");
                });
#pragma warning restore 612, 618
        }
    }
}
